<section class="home__message">
  <h3>Message</h3>

  {% include '../../../project/header/header.html.swig' %}

  {% set offer = offers[0] %}
  {% include '../../../project/offer/offer.html.swig' %}

  {% include '../../../project/focus-points/focus-points.html.swig' %}
  {% include '../../../project/see-more/see-more.html.swig' %}
  {% include '../../../project/see-portfolio/see-portfolio.html.swig' %}
</section>
